name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      NODE_VERSION: 18
      JAVA_VERSION: "17"
      SDK_VERSION_MAJOR: 5.0.5
      SDK_VERSION_MINOR: 310
      URL_BASE: "https://repo.huaweicloud.com/openharmony/ohpm"
      FILE_BASENAME: "commandline-tools-linux-x64"
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup OpenHarmony SDK
        id: setup-sdk
        run: |
          # Prepare path
          export CMDLINE_TOOL_DIR="${HOME}/setup-sdk"
          mkdir -p "${CMDLINE_TOOL_DIR}"
          
          # Download commandline tools and unzip
          curl -L -o "${CMDLINE_TOOL_DIR}/${FILE_BASENAME}.zip" "${URL_BASE}/${SDK_VERSION_MAJOR}/${FILE_BASENAME}-${SDK_VERSION_MAJOR}-${SDK_VERSION_MINOR}.zip"
          unzip "${CMDLINE_TOOL_DIR}/${FILE_BASENAME}.zip" -do "${CMDLINE_TOOL_DIR}"
          
          # Setup environment variables
          export PATH=${CMDLINE_TOOL_DIR}/command-line-tools/bin:$PATH
          
          # Setup npm registry
          npm config set registry https://repo.huaweicloud.com/repository/npm/
          npm config set "@ohos:registry" https://repo.harmonyos.com/npm/
          
          # Setup ohpm
          ohpm -v
          ohpm config set registry https://ohpm.openharmony.cn/ohpm/
          ohpm config set strict_ssl false

      - name: Build HAP
        run: |
          # Install dependencies
          ohpm install --all
          
          # Build product
          hvigorw -v
          hvigorw clean --no-daemon
          hvigorw assembleHap --mode module -p product=default --parallel --no-daemon

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: entry-default-unsigned.hap
          path: entry/build/default/outputs/default/entry-default-unsigned.hap

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
