name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    env:
      OHOS_SDK_VERSION: 5.0.1
      NODE_VERSION: 18
      JAVA_VERSION: "17"
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup OpenHarmony SDK
        id: setup-sdk
        uses: openharmony-rs/setup-ohos-sdk@v0.2
        with:
          version: ${{ env.OHOS_SDK_VERSION }}

      - name: Install hvigor
        run: |
          npm config set "@ohos:registry" https://repo.harmonyos.com/npm/
          npm install "@ohos/hvigor"
          npm install "@ohos/hvigor-ohos-plugin"

      - name: Build HAP
        run: |
          node ./node_modules/@ohos/hvigor/bin/hvigor.js --mode module -p product=default assembleHap --parallel --no-daemon

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: entry-default-unsigned.hap
          path: entry/build/default/outputs/default/entry-default-unsigned.hap

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
